---
- name: find card reader (SCR3310-NTTCom)
  shell: lsusb | grep 'SCM Microsystems, Inc.'
  register: lsusb_result
  check_mode: no

- set_fact:
    card_reader_bus: "{{ lsusb_result.stdout.split(' ')[1] }}"
    card_reader_dev: "{{ lsusb_result.stdout.split(' ')[3][:-1] }}"

- name: set custom docker-compose.yml
  template:
    src: docker-compose.yml
    dest: "{{ docker_mirakurun_epgstation_path}}/docker-compose.yml"

- name: mirakurun settings
  copy:
    src: "{{ item }}"
    dest: "{{ docker_mirakurun_epgstation_path}}/{{ item }}"
  with_items:
    - mirakurun/conf/server.yml
    - mirakurun/conf/tuners.yml

- name: use H264 OMX encoding
  lineinfile:
    path: "{{ docker_mirakurun_epgstation_path}}/epgstation/config/enc.js"
    regexp: "const codec = 'libx264';"
    line: "const codec = 'h264_omx';"

- name: use H264 OMX encoding (streaming)
  replace:
    path: "{{ docker_mirakurun_epgstation_path}}/epgstation/config/config.json"
    regexp: "-c:v libx264"
    replace: "-c:v h264_omx"
