---
- name: clone docker-mirakurun-epgstation
  git:
    repo: 'https://github.com/l3tnun/docker-mirakurun-epgstation.git'
    dest: "{{ docker_mirakurun_epgstation_path }}"
    force: true

- name: fix EPGStation Dockerfile (to avoid build error)
  lineinfile:
    path: "{{ docker_mirakurun_epgstation_path }}/epgstation/Dockerfile"
    line: '    apt-get -y install python && \'
    insertafter: 'apt-get -y install libasound2'

- name: fix EPGStation Dockerfile (ffmpeg h264_omx)
  blockinfile:
    path: "{{ docker_mirakurun_epgstation_path }}/epgstation/Dockerfile"
    block: |
      # ffmpeg libs
      \
      apt-get -y install cmake sudo libomxil-bellagio-dev && \
      cd /root && \
      git clone --depth 1 https://github.com/raspberrypi/userland.git && \
      cd /root/userland && \
      ./buildme && \
      \
      echo "/opt/vc/lib" > /etc/ld.so.conf.d/00-vmcs.conf && \
      ldconfig && \
      \
    marker: '# {mark} ANSIBLE MANAGED BLOCK (ffmpeg libs)'
    insertbefore: '#ffmpeg build'

- name: fix EPGStation Dockerfile (ffmpeg h264_omx)
  lineinfile:
    path: "{{ docker_mirakurun_epgstation_path }}/epgstation/Dockerfile"
    regexp: '--enable-libx264'
    line: '      --enable-libx264 --enable-mmal --enable-omx-rpi --enable-omx \'

- name: fix mirakurun Dockerfile (to use PX-S1UD)
  blockinfile:
    path: "{{ docker_mirakurun_epgstation_path }}/mirakurun/Dockerfile"
    block: |
      # recdvb
      \
      apt-get -y install wget && \
      cd /tmp && \
      wget http://www13.plala.or.jp/sat/recdvb/recdvb-{{ recdvb_version }}.tgz -O recdvb-{{ recdvb_version }}.tgz && \
      tar zxf recdvb-{{ recdvb_version }}.tgz && \
      cd recdvb-{{ recdvb_version }} && \
      ./autogen.sh && \
      ./configure && \
      make && \
      make install && \
      \
    marker: '# {mark} ANSIBLE MANAGED BLOCK (recdvb)'
    insertbefore: '# recpt1'

- name: build
  shell: docker-compose build
  args:
    chdir: "{{ docker_mirakurun_epgstation_path }}"
