---
- name: install docker-mirakurun-epgstation
  import_tasks: install.yml
  tags: install_docker_mirakurun_epgstation

- name: install drivers
  import_tasks: drivers.yml
  tags: install_tuner_drivers

- name: config docker-mirakurun-epgstation
  import_tasks: config.yml
  tags: config_docker_mirakurun_epgstation
