---
- name: clone docker-mirakurun-epgstation
  git:
    repo: 'https://github.com/l3tnun/docker-mirakurun-epgstation.git'
    dest: "{{ docker_mirakurun_epgstation_path }}"
    force: true

- name: fix Dockerfile (to fix build error)
  replace:
    path: "{{ docker_mirakurun_epgstation_path }}/epgstation/Dockerfile"
    regexp: 'build-essential python3'
    replace: 'build-essential python python3'

- name: build
  shell: docker-compose build
  args:
    chdir: "{{ docker_mirakurun_epgstation_path }}"

- name: set custom docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: "{{ docker_mirakurun_epgstation_path}}/docker-compose.yml"
