---
- name: create users
  user:
    name: "{{ item.name }}"
    group: "{{ item.group }}"
  with_items: "{{ users }}"

- name: put authorized key
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.authorized_key }}"
  with_items: "{{ users }}"

- name: enable sudo without password
  copy:
    dest: "/etc/sudoers.d/010_{{ item.name }}-nopasswd"
    content: "{{ item.name }} ALL=(ALL) NOPASSWD: ALL"
  when: item.group == "sudo"
  with_items: "{{ users }}"
