---
- name: install rfkill
  package:
    name: rfkill
    state: present

- name: unblock wifi
  shell: rfkill unblock wifi

- name: connect wifi
  template:
    src: wpa_supplicant.conf.j2
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
    owner: root
    group: root
    mode: '0600'

- name: set static ip address
  blockinfile:
    path: /etc/dhcpcd.conf
    block: |
      interface wlan0
      static ip_address=192.168.11.201/24
      static routers=192.168.11.1
      static domain_name_servers=192.168.11.1
