---
- name: install docker
  shell: curl -sSL https://get.docker.com | sh

- name: enable docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: add users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items:
    - pi
    - castor
